### ISSUE TITLE
Example contains invalid spec, missing image

### ISSUE THREAD

**Issue by stub42** [juju-solutions/layer-caas-base#10]
The example in README.md has a pod spec using an imageDetails map instead of an image key. This is rejected by caas_base.pod_spec_set(), logging the error 'ERROR invalid pod spec: spec image is missing'.

**Comment by johnsca** [comment]
The `imageDetails` map was added with the support for the `docker` (soon to be `osi-image`) resource type.  It's been working fine for me with that pattern for at least a week or two.  I wonder if the error message is misleading and masking some other issue?

**Comment by stub42** [comment]
It works as documented with 2.5 edge
