### ISSUE TITLE
charm build with this layer currently fails

### ISSUE THREAD

**Issue by mthaddon** [juju-solutions/layer-caas-base#27]
I originally filed https://github.com/juju/charm-tools/issues/594 but Cory mentioned it's actually an issue in layer-caas-base, so filing here instead.

**Comment by johnsca** [comment]
Upon further review, this actually came in from https://github.com/juju/charm-tools/pull/585 (specifically, [this section](https://github.com/juju/charm-tools/pull/585/files#diff-ed28d309f96602c0413266af4535f3106d2f02a41fdc6b354b1466693df3a5dcR399-R419)).  So closing this and moving it back upstream.

**Comment by johnsca** [comment]
Re-opening because it can more easily be fixed in this layer.
